Repository MoigeMatino/African-Recipes-Api, pull requests merged in 2023-05, with the labels that each got.

#25 chore: update dependencies
  poetry.lock
  pyproject.toml
Labels: running-updates

#28 Revert: Undo relative file imports
  .gitignore
  app/models.py
  app/utils.py
Labels: ready-for-review

#34 Bug fixes
  alembic/versions/c369dc1fd7dd_update_user_and_image_relationship_and_.py
Labels: bug, ready-for-review, migrations

#35 chore: add dependencies for formatting
  .flake8
  Dockerfile
  app/config.py
  app/constants.py
  app/db/base_class.py
  app/db/db.py
  app/models.py
  app/routes.py
  app/schemas.py
  app/utils.py
  docker-compose.yml
  poetry.lock
  pyproject.toml
  scripts/format.sh
  scripts/lint.sh
  tests/__init__.py
  tests/create-testing-database.sql
Labels: enhancement, ready-for-review

#41 feat: update recipe serializers
  app/routes.py
  app/schemas.py
  app/serializers/__init__.py
  app/serializers/recipe.py
  app/utils.py
Labels: enhancement, ready-for-review
